# Generated by Django 2.0.3 on 2021-10-27 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='animal',
            table='animal',
        ),
    ]
